### ISSUE TITLE
S3 bucket or other place to host vector tiles

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/VectorTilesDemo#1]
Need a place to host the tiles. Initial pilot is running them from my EC2 "playground" which won't be around forever, and which does not support HTTPS.

- [x] Set up AWS org and/or accounts.
- [x] Generate API key
- [x] Set up S3 bucket.
- [x] Upload tiles
- [x] Adjust demo to use new tile source.

**Comment by danrademacher** [comment]
Breaking out first Item above:
- [x] @GWHAThistory creates an AWS account here: https://aws.amazon.com/free, if possible using an `@openhistoricalmap.org` email address (do these exist?) or even `openhistoricalmap@gmail.com` or similar that could be transferred to any future owners of the larger open source project. Ideally that email would have 2FA enabled to help lock down core AWS access / phishing attacks.
- [x] I'll screenshare with @GWHAThistory to make an IAM for me and an Admin Group to which I belong
- [x] I'll then add others to have dev access.

**Comment by jeffreyameyer** [comment]
No openhistoricalmap.org email addresses right now. I could probably get these set up, but will need to check with the group. Noted / good call on 2FA.

**Comment by rwarren2** [comment]
Addresses will need to wait till the domain is re-hosted.

**Comment by danrademacher** [comment]
@gregallensworth new bucket here: https://s3.console.aws.amazon.com/s3/buckets/ohm-demo

I think IAM setup should cover your access to get API keys that you need.
