### ISSUE TITLE
Time slider: add year readout, next/prev/play/stop UI

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/VectorTilesDemo#3]
Time slider has basic functionality, but not yet UI considerations:
* play/prev/next/stop buttons to automate the show
* readout to show the current year

**Comment by jeffreyameyer** [comment]
Let's hold off on any play / pause functionality for now.

Definitely need to show a "current" time in some way.

Some timeslider examples here: https://docs.google.com/presentation/d/1876erCftYtsRJwWvrSM3f-N5n_7aFUpQmbUxn7dQ_8M/edit#slide=id.g38dd368be4_0_0

Simpler is better to start, for sure. 😀

**Comment by gregallensworth** [comment]
Gregor: Change the step value from 10 years to 5, for finer resolution. On the larger time scale of the world 10 or even 100 years may be fine, but for this limited time period of 240 years finer resolution would be nice.

Maybe even single-year resolution could work. 768 px to cover 200 years = 4px per year, in the "worst" possible case that we would care to support.
