### ISSUE TITLE
Layer picker

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/VectorTilesDemo#4]
At present there is no layer picker. Need to toggle historical state/county and to toggle modern state/county individually.

**Comment by jeffreyameyer** [comment]
Should this be done with layers or styling at zoom levels? e.g. only show counties when zoomed in to roughly state level?

**Comment by gregallensworth** [comment]
Layer visibility comes in two parts:

* The availability of the layer at the given zoom level. With the data as-given from Newberry, State tiles cannot be generated without significant artifacts only up to z3, and Counties cannot start before z6. (not to say it's impossible, but would require significant contrivances not yet figured out, suited to a second round once the basic UI and UX are standing up)
  * Within the vectile configuration, the map knows not to try loading tiles for inappropriate zoom levels.

* Setting the layer to `visibility: none` or `visibility: visible` This is what the layer control will do, so a user may manually choose to show historical states, modern states, historical counties, and modern counties in any combination.
  * Such a manual control, also lays a foundation for other layer adjustments not yet determined, such as opacity sliders, alternative basemaps, a choice of label overlay, additional reference layers not yet defined, ...

**Comment by jeffreyameyer** [comment]
I'm surprised to hear about the artifacts in the State-level Newberry data. Can you send a screenshot of what you're seeing? Here's an example of Kentucky that I think looks pretty good at about zoom = 9 or 10: https://imgur.com/a/HhbyTGA
