### ISSUE TITLE
Tooltip behavior

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/VectorTilesDemo#5]
Tooltip behavipor in place at present, is placeholder to show what's there. Needs design, or rethinking as to desired behaviors. Should this happen only on a click for example, while hover shows a smaller tooltip?

**Comment by jeffreyameyer** [comment]
I think it depends on the presence of a panel-based inspector. A few examples of these here: https://docs.google.com/presentation/d/1876erCftYtsRJwWvrSM3f-N5n_7aFUpQmbUxn7dQ_8M/edit#slide=id.g38dd368be4_0_11

What about something "simple" (?), with no tooltips - 
- Hover = highlights selectability of underlying shape
- Click = update inspector panel

?

**Comment by gregallensworth** [comment]
Gregor: Change behavior of the InspectorPanelControl, to perform a point query instead of nearby-box query. Have this drill down through all layers and report *all hits* for this point:  modern state & county, historical state & county presence at that point.

- [x] enable the transparent-fill always-on modern state & county layers; so they can be queried
- [x] set up transparent-fill always-on historical states & counties layers; so they can be queried
- [x] rewrite search behavior to use point against these transparent layers
- [x] unique-ify resultset, and sort by `START` date
- [ ] maybe a toggle behavior in the inspector panel, so the title and dates show first, and verbose narrative not until a "more" button is clicked

Also, given the lengthy nature of this listing:
- [x] add max-height & scrolling behavior
- [ ] add X to close this panel, as it's not necessarily obvious nor readily feasible, to click someplace else where there is nothing, in order to close the panel

And new features:
- [ ] upon clicking a feature, can we highlight it on the map? The hover layer being separate from the displayed layers, this should work well to illustrate that modern/past area in contrast to the visible areas.
