### ISSUE TITLE
Transitions during year changes

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/VectorTilesDemo#8]
When changing from one year to the next (`YearPickerControl`) is it possible to introduce some sort of easing effect?

Possible methodology:
* have 2 copies of the states/counties vectors, only one visible at a time
* upon a year change, apply the filter to the "new" layer, and ...
* ... begin a timer which sets the opacity of the "old" display from 1 to 0, and the "new" display from 0 to 1; when one reaches 0, set `visibility: none`

Could be complicated, particularly if we introduce user-defined opacity (opacity sliders) which would need to be kept in sync to two different sets of layers, and as we break apart the layers into more sub-layers (e.g. counties, broken up for color-classification, for county, township, etc.) and keeping potentally dozens of layer in sync...

**Comment by jeffreyameyer** [comment]
This could be tricky, too, with a fickle-fingered user who flicks across several stops on the timeline quickly...
